# Generated by Django 4.1.2 on 2022-12-18 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        ('system_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system_admin.cinema'),
        ),
        migrations.AddField(
            model_name='screen',
            name='facility',
            field=models.ManyToManyField(blank=True, to='cinema.facility'),
        ),
        migrations.AddField(
            model_name='movieshowseat',
            name='movie_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.movieshow'),
        ),
        migrations.AddField(
            model_name='movieshow',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_admin.movie'),
        ),
        migrations.AddField(
            model_name='movieshow',
            name='screen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.screen'),
        ),
    ]
