# Generated by Django 4.1.2 on 2022-12-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='admin',
            field=models.ManyToManyField(blank=True, to='user.profile'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.city'),
        ),
    ]
