# Generated by Django 4.1.2 on 2022-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
