# Generated by Django 4.1.2 on 2022-12-19 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('cinema', '0002_initial'),
        ('user', '0001_initial'),
        ('booking', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinformation',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema'),
        ),
        migrations.AddField(
            model_name='paymentinformation',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod'),
        ),
        migrations.AddField(
            model_name='paid',
            name='booking_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.bookingrequest'),
        ),
        migrations.AddField(
            model_name='paid',
            name='payment_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymentinformation'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentinformation',
            unique_together={('cinema', 'payment_method')},
        ),
        migrations.AlterUniqueTogether(
            name='paid',
            unique_together={('booking_request', 'payment_info', 'transaction_id')},
        ),
    ]
