# Generated by Django 4.1.2 on 2022-12-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('cinema', '0002_facility_alter_movieshow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='movie_show_seat',
            field=models.ManyToManyField(blank=True, to='cinema.movieshowseat'),
        ),
    ]
