# Generated by Django 4.1.2 on 2022-12-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='movie_show_seat',
            field=models.ManyToManyField(blank=True, to='cinema.movieshowseat'),
        ),
    ]
