# Generated by Django 4.1.2 on 2022-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='crew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
